---
- name: monitor nginx
  template:
    src: nginx.conf
    dest: "{{ monit_configs_dir }}/nginx.conf"
    owner: root
    group: root
    mode: 0644
  when: monitoring_track_nginx
  notify:
    - reload monit

- name: monitor postfix
  template:
    src: postfix.conf
    dest: "{{ monit_configs_dir }}/postfix.conf"
    owner: root
    group: root
    mode: 0644
  when: monitoring_track_postfix
  notify:
    - reload monit

- name: monitor postgres
  template:
    src: postgres.conf
    dest: "{{ monit_configs_dir }}/postgres.conf"
    owner: root
    group: root
    mode: 0644
  when: monitoring_track_postgres
  notify:
    - reload monit

