---
- name: install the pgbouncer package
  apt:
    name: pgbouncer
    state: present
  notify:
    - restart pgbouncer

- name: create the config file
  template:
    src: pgbouncer.ini.j2
    dest: "{{ pgbouncer_conf_dir }}/pgbouncer.ini"
    owner: "{{ pgbouncer_user }}"
    group: "{{ pgbouncer_group }}"
    mode: 0600
  register: pgbouncer_config_result

- name: restart pgbouncer in response to config changes
  service:
    name: pgbouncer
    state: restarted
  when: pgbouncer_config_result.changed

- name: create the users file
  template:
    src: userlist.txt.j2
    dest: "{{ pgbouncer_users_file }}"
    owner: "{{ pgbouncer_user }}"
    group: "{{ pgbouncer_group }}"
    mode: 0600

- name: run pgbouncer at boot
  service:
    name: pgbouncer
    enabled: yes
    state: started
