#!/bin/bash

APPS=(chiton himation)

case $1 in
"chiton")
  ssh chiton@development-www.coveryourbasics.com
  ;;
"himation")
  ssh himation@development-www.coveryourbasics.com
  ;;
*)
  echo "Usage: develop APP"
  echo
  echo "       APP: The name of an application (${APPS[*]})"
  exit 1
  ;;
esac
