#!/bin/bash

VMS=(chiton himation)

case $1 in
"chiton")
  ssh chiton@development-data.coveryourbasics.com
  ;;
"himation")
  ssh himation@development-www.coveryourbasics.com
  ;;
*)
  echo "Usage: develop VM"
  echo
  echo "       VM: The ID of a virtual machine (${VMS[*]})"
  exit 1
  ;;
esac
