Vagrant.configure(2) do |config|

  require_relative "../fibula"

  config.vm.define("himation-development") do |himation|
    hostname = Fibula.hostname("himation-development")
    host_vars = Fibula.ansible_host_vars(hostname)

    himation.vm.box = "fibula/ubuntu-14.04"
    himation.vm.hostname = hostname

    himation.vm.network "private_network", ip: host_vars.fetch("himation_app_server").fetch("host")

    himation.ssh.insert_key = false
    himation.ssh.private_key_path = Fibula.private_key_path
    himation.ssh.forward_agent = true
    himation.ssh.username = ENV["HIMATION_SSH_USER"]

    himation.vm.synced_folder *Fibula.sync_home_options(host_vars.fetch("vagrant_host_home_dir"))
    himation.vm.synced_folder *Fibula.sync_guest_nfs_dir_options({
      group_id: host_vars.fetch("himation_group_id"),
      guest: host_vars.fetch("himation_source_dir"),
      host: ENV.fetch("CYB_NFS_DIR_HIMATION"),
      user_id: host_vars.fetch("himation_user_id")
    })

    himation.vm.provider "virtualbox" do |vbox|
      vbox.cpus = 2
      Fibula.virtualbox_networking_optimizations.each do |optimization|
        vbox.customize optimization
      end
    end

  end

  config.vm.define("chiton-development") do |chiton|
    hostname = Fibula.hostname("chiton-development")
    host_vars = Fibula.ansible_host_vars(hostname)

    chiton.vm.box = "fibula/ubuntu-14.04"
    chiton.vm.hostname = hostname

    chiton.vm.network "private_network", ip: host_vars.fetch("chiton_server_address")

    chiton.ssh.insert_key = false
    chiton.ssh.private_key_path = Fibula.private_key_path
    chiton.ssh.forward_agent = true
    chiton.ssh.username = ENV["CHITON_SSH_USER"]

    chiton.vm.synced_folder *Fibula.sync_home_options(host_vars.fetch("vagrant_host_home_dir"))
    chiton.vm.synced_folder *Fibula.sync_guest_nfs_dir_options({
      group_id: host_vars.fetch("chiton_group_id"),
      guest: host_vars.fetch("chiton_source_dir"),
      host: ENV.fetch("CYB_NFS_DIR_CHITON"),
      user_id: host_vars.fetch("chiton_user_id")
    })

    chiton.vm.provider "virtualbox" do |vbox|
      vbox.cpus = 2
      Fibula.virtualbox_networking_optimizations.each do |optimization|
        vbox.customize optimization
      end
    end

  end

end
