---
- name: reload postfix
  service:
    name: postfix
    state: reloaded

- name: restart postfix
  service:
    name: postfix
    state: restarted

- name: rebuild mail aliases
  command: newaliases

- name: rebuild virtual aliases
  command: postmap {{ postfix_virtual_aliases_file }}
