---
- name: create the directory for collected assets
  file:
    path: "{{ chiton_assets_dir }}"
    owner: "{{ chiton_user }}"
    group: "{{ chiton_group }}"
    mode: 0755
    state: directory

- name: collect the assets
  command: "{{ chiton_manage_file | quote }} collectstatic --clear --noinput"
  environment:
    CHITON_CONFIG_FILE: "{{ chiton_config_file }}"
