---
- name: create an application configuration file
  template:
    src: config.json.j2
    dest: "{{ chiton_config_file }}"
    owner: "{{ chiton_user }}"
    group: "{{ chiton_group }}"
    mode: 0600
  notify:
    - reload chiton

- name: create a New Relic configuration file
  template:
    src: newrelic.ini.j2
    dest: "{{ chiton_new_relic_config_file }}"
    owner: "{{ chiton_user }}"
    group: "{{ chiton_group }}"
    mode: 0600
  notify:
    - reload chiton

- name: create a gunicorn configuration file
  template:
    src: gunicorn.py.j2
    dest: "{{ chiton_gunicorn_config_file }}"
    owner: "{{ chiton_user }}"
    group: "{{ chiton_group }}"
    mode: 0600
  notify:
    - reload chiton

- name: create a profile script to customize the application user's environment
  template:
    src: profile.j2
    dest: "{{ chiton_user_custom_profile }}"
    owner: "{{ chiton_user }}"
    group: "{{ chiton_group }}"
    mode: 0600

- name: ensure that the application user loads the custom profile
  lineinfile:
    dest: "{{ chiton_user_home_dir }}/.profile"
    line: ". {{ chiton_user_custom_profile }}"
    state: present
    owner: "{{ chiton_user }}"
    group: "{{ chiton_group }}"
    mode: 0600
