---
- name: create an application configuration file
  template:
    src: config.json.j2
    dest: "{{ chiton_config_file }}"
    owner: "{{ chiton_user }}"
    group: "{{ chiton_group }}"
    mode: 0600

- name: create a master uWSGI configuration file
  template:
    src: uwsgi-master.ini.j2
    dest: "{{ chiton_master_uwsgi_ini_file }}"
    owner: "{{ chiton_user }}"
    group: "{{ chiton_group }}"
    mode: 0600
  notify:
    - restart chiton

- name: create a slave uWSGI configuration file
  template:
    src: uwsgi-slave.ini.j2
    dest: "{{ chiton_slave_uwsgi_ini_file }}"
    owner: "{{ chiton_user }}"
    group: "{{ chiton_group }}"
    mode: 0600
  notify:
    - reload chiton

- name: create a profile script to customize the application user's environment
  template:
    src: profile.j2
    dest: "{{ chiton_user_custom_profile }}"
    owner: "{{ chiton_user }}"
    group: "{{ chiton_group }}"
    mode: 0600

- name: ensure that the application user loads the custom profile
  lineinfile:
    dest: "{{ chiton_user_home }}/.profile"
    line: ". {{ chiton_user_custom_profile }}"
    state: present
    owner: "{{ chiton_user }}"
    group: "{{ chiton_group }}"
    mode: 0600

- name: create a management command
  template:
    src: manage.py.j2
    dest: "{{ chiton_manage_file }}"
    owner: "{{ chiton_user }}"
    group: "{{ chiton_group }}"
    mode: 0755
