---
- name: add the custom Vagrant key to the application user's authorized keys
  copy:
    dest: "{{ chiton_user_ssh_dir.path }}/authorized_keys"
    content: "{{ chiton_vagrant_ssh_key }}"
    mode: 0600

- name: fetch the source code
  git:
    accept_hostkey: yes
    clone: yes
    dest: "{{ chiton_source_dir }}"
    repo: git@github.com:justinlocsei/chiton.git
    update: yes
    version: "{{ chiton_git_branch }}"

- name: install all dependencies in a virtualenv
  pip:
    requirements: "{{ chiton_requirements_dir }}/{{ item }}"
    executable: "{{ python_pip_executable }}"
    virtualenv: "{{ chiton_virtualenv_dir }}"
    virtualenv_python: "{{ python_executable }}"
    virtualenv_site_packages: no
    state: present
  with_items:
    - core.txt
    - development.txt

- name: activate the virtualenv for the application user at login
  lineinfile:
    dest: "{{ chiton_user_details.home }}/.profile"
    line: "cd \"{{ chiton_source_dir }}\" && source {{ chiton_virtualenv_dir }}/bin/activate"
    state: present
