---
- name: run pending database migrations
  command: "{{ chiton_manage_file | quote }} migrate"
  environment:
    CHITON_CONFIG_FILE: "{{ chiton_config_file }}"
  register: chiton_migrate_result
  changed_when: "'No migrations to apply.' not in chiton_migrate_result.stdout"

- name: create the in-app administrator account
  command: "{{ chiton_manage_file | quote }} chiton_ensuresuperuser --username {{ chiton_admin_username | quote }} --email {{ chiton_admin_email | quote }} --password {{ chiton_admin_password | require_value | quote }}"
  environment:
    CHITON_CONFIG_FILE: "{{ chiton_config_file }}"
  no_log: yes
  register: chiton_ensuresuperuser_result
  changed_when: "'User modified' in chiton_ensuresuperuser_result.stdout"

- name: load core fixtures
  command: "{{ chiton_manage_file | quote }} chiton_loadfixtures"
  environment:
    CHITON_CONFIG_FILE: "{{ chiton_config_file }}"
