---
- name: install image packages required for building Pillow
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - libjpeg8-dev
    - liblcms2-dev
    - libwebp-dev
    - zlib1g-dev
