---
- name: install image packages required for building Pillow
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - libjpeg8-dev
    - liblcms2-dev
    - libwebp-dev
    - zlib1g-dev

- name: install packages for building libsodium
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - libffi-dev
