---
- name: add a robots.txt file
  copy:
    src: public/robots.txt
    dest: "{{ chiton_public_files_dir }}/robots.txt"
    owner: "{{ chiton_user }}"
    group: "{{ chiton_group }}"
    mode: 0644
