---
- name: install trusted CA certificates
  apt:
    name: ca-certificates
    state: present

- name: create a CA certificate for self-signed certificates
  copy:
    dest: "{{ cyb_certificates_ca_certificate_path }}"
    owner: root
    group: root
    mode: 0644
    content: "{{ cyb_certificates_wildcard_certificate }}\n"
  register: cyb_certificates_copy
  when: not cyb_certificates_wildcard_ca_bundle

- name: re-hash the certificates
  command: update-ca-certificates --fresh
  when: cyb_certificates_copy.changed
