---
- name: create swap space
  command: dd if=/dev/zero of={{ common_swap_file }} bs=1M count={{ ansible_memtotal_mb * 2 }}

- name: make swap
  command: mkswap {{ common_swap_file }}

- name: add the swap to fstab
  lineinfile:
    dest: /etc/fstab
    regexp: "{{ common_swap_file }}"
    line: "{{ common_swap_file }} none swap sw 0 0"
    state: present

- name: enale swap
  command: swapon -a

- name: set swappiness
  sysctl:
    name: vm.swappiness
    value: 1
