---
- name: ensure that cron is available
  apt:
    name: cron
    state: present

- name: use a valid address for cron emails
  cronvar:
    name: MAILTO
    value: "{{ cron_mailto }}"
    state: present

- name: install the cronic wrapper script
  template:
    src: cronic.j2
    dest: "{{ cron_runner }}"
    owner: root
    group: root
    mode: 0755
