require_relative "../fibula"

Vagrant.configure(2) do |config|
  config.vm.define("himation") do |himation|

    himation.vm.box = "fibula/ubuntu-14.04"
    himation.vm.hostname = "himation"

    himation.vm.network "private_network", ip: Fibula.ip(:himation)
    himation.vm.network "forwarded_port", guest: 8080, host: Fibula.port(:himation)

    himation.ssh.insert_key = false
    himation.ssh.private_key_path = Fibula.private_key_path

    himation.vm.synced_folder Fibula.project_directory("himation"), "/var/himation-nfs", Fibula.nfs_options
    himation.bindfs.bind_folder "/var/himation-nfs", "/var/himation", Fibula.bindfs_options

    himation.vm.provision "ansible" do |ansible|
      ansible.playbook = Fibula.ansible_file("himation.yml")
      ansible.sudo = true
      ansible.verbose = "v"
    end

  end
end
