require_relative "../fibula"

Vagrant.configure(2) do |config|
  config.vm.define("himation") do |himation|

    himation.vm.box = Fibula.box_path("ubuntu-14.04-0.1.0")
    himation.vm.hostname = "himation"

    himation.vm.network "private_network", ip: Fibula.ip(:himation)
    himation.vm.network "forwarded_port", guest: 8080, host: Fibula.port(:himation)

    himation.ssh.insert_key = false
    himation.ssh.private_key_path = Fibula.private_key_path

    himation.vm.provision "ansible" do |ansible|
      ansible.playbook = Fibula.ansible_file("himation.yml")
      ansible.sudo = true
      ansible.verbose = "v"
    end

  end
end
