require_relative "../helpers"

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.hostname = "himation"

  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "private_network", ip: "10.10.10.10"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = Helpers.ansible_playbook("webservers")
    ansible.sudo = true
    ansible.verbose = "v"
  end

end
