---
- name: install the New Relic APT key
  apt_key:
    url: https://download.newrelic.com/548C16BF.gpg
    state: present

- name: add the New Relic APT repository
  apt_repository:
    repo: deb http://apt.newrelic.com/debian/ newrelic non-free
    state: present

- name: install the New Relic server daemon
  apt:
    name: newrelic-sysmond
    state: present

- name: create the New Relic configuration file
  template:
    src: nrsysmond.cfg.j2
    dest: /etc/newrelic/nrsysmond.cfg
    owner: newrelic
    group: newrelic
    mode: 0640
  notify:
    - restart New Relic

- name: run the New Relic daemon at boot
  service:
    name: "{{ new_relic_service }}"
    enabled: yes
    state: started
  when: new_relic_enabled

- name: disable the New Relic daemon
  service:
    name: "{{ new_relic_service }}"
    enabled: no
    state: stopped
  when: not new_relic_enabled
