---
- name: create the build directories
  file:
    path: "{{ item }}"
    owner: "{{ cyb_deb_builder_user }}"
    group: "{{ cyb_deb_builder_group }}"
    mode: 0755
    state: directory
  with_items:
    - "{{ cyb_deb_builder_root_dir }}"
    - "{{ cyb_deb_builder_packages_dir }}"
    - "{{ cyb_deb_builder_build_dir }}"
    - "{{ cyb_deb_builder_repo_root_dir }}"
    - "{{ cyb_deb_builder_repo_packages_dir }}"
    - "{{ cyb_deb_builder_repo_conf_dir }}"
    - "{{ cyb_deb_builder_repo_meta_dir }}"

- name: create the repo configuration files
  template:
    src: "{{ item }}.j2"
    dest: "{{ cyb_deb_builder_repo_conf_dir }}/{{ item }}"
    owner: "{{ cyb_deb_builder_user }}"
    group: "{{ cyb_deb_builder_group }}"
    mode: 0644
  with_items:
    - distributions
    - options

- name: add the public signing key to the repository
  copy:
    dest: "{{ cyb_deb_builder_repo_meta_dir }}/cyb.key"
    content: "{{ cyb_deb_builder_gpg_signing_key_public }}"
    owner: "{{ cyb_deb_builder_user }}"
    group: "{{ cyb_deb_builder_group }}"
    mode: 0644

- name: create the build scripts
  template:
    src: "{{ item }}.j2"
    dest: "{{ cyb_deb_builder_root_dir }}/{{ item }}"
    owner: "{{ cyb_deb_builder_user }}"
    group: "{{ cyb_deb_builder_group }}"
    mode: 0755
  with_items:
    - build-package
    - create-repo
