---
- name: sync user configuration files
  file:
    src: "{{ vagrant_host_home_dir }}/{{ item }}"
    dest: "/home/{{ vagrant_host_user }}/{{ item }}"
    owner: "{{ vagrant_host_user }}"
    group: "{{ vagrant_host_group }}"
    force: yes
    state: link
  with_items:
    - .gitconfig
    - .tmux.conf
