---
- name: create the KeyCDN group
  group:
    name: "{{ keycdn_group }}"
    state: present

- name: create the KeyCDN user
  user:
    name: "{{ keycdn_user }}"
    group: "{{ keycdn_group }}"
    comment: "KeyCDN system user"
    system: yes
    state: present

- name: create the configuration directory
  file:
    path: "{{ keycdn_config_dir }}"
    owner: "{{ keycdn_user }}"
    group: "{{ keycdn_group }}"
    mode: 0750
    state: directory

- name: create the SSH keys for using rsync
  copy:
    dest: "{{ item.dest }}"
    content: "{{ item.content }}"
    owner: "{{ keycdn_user }}"
    group: "{{ keycdn_group }}"
    mode: 0640
  with_items:
    - dest: "{{ keycdn_private_key_path }}"
      content: "{{ keycdn_private_key }}"
    - dest: "{{ keycdn_public_key_path }}"
      content: "{{ keycdn_public_key }}"

- name: create the sync script
  template:
    src: templates/sync.sh.j2
    dest: "{{ keycdn_syncer_bin }}"
    owner: "{{ keycdn_user }}"
    group: "{{ keycdn_group }}"
    mode: 0755
