#!/bin/bash

SCRIPTS_DIR="$(dirname "${BASH_SOURCE[0]}")/../../scripts"
source "$SCRIPTS_DIR"/env/develop.sh

fib deploy bootstrap apt --inventory=development --user=vagrant --playbook=repo.yml --force "$@"
