Vagrant.configure(2) do |config|

  require_relative "../fibula"

  config.vm.define("apt", primary: true) do |config|
    config.vm.box = "fibula/ubuntu-14.04"
    config.vm.hostname = Fibula.hostname("apt")
    config.hostsupdater.remove_on_suspend = false

    config.vm.network "private_network", ip: "10.40.40.40"

    config.ssh.insert_key = false
    config.ssh.private_key_path = Fibula.private_key_path
    config.ssh.forward_agent = true

    config.vm.provider "virtualbox" do |vbox|
      vbox.cpus = 2
      Fibula.virtualbox_networking_optimizations.each do |optimization|
        vbox.customize optimization
      end
    end

  end

end
