- name: build assets
  command: npm run build
  args:
    chdir: "{{ himation_current_version_source_dir }}"
  environment:
    HIMATION_CONFIG_FILE: "{{ himation_config_file }}"
    NODE_ENV: "{{ himation_node_env }}"
  become: yes
  become_user: "{{ himation_user }}"
