---
- name: create scripts to run tasks with the correct environment
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ himation_user }}"
    group: "{{ himation_group }}"
    mode: 0755
  with_items:
    - src: gulp.j2
      dest: "{{ himation_gulp_runner }}"
    - src: npm.j2
      dest: "{{ himation_npm_runner }}"

- name: build assets
  command: "{{ himation_npm_runner | quote }} build"
  become: yes
  become_user: "{{ himation_user }}"
  changed_when: False
