---
- name: create an application configuration file
  template:
    src: settings.json.j2
    dest: "{{ himation_config_file }}"
    owner: "{{ himation_user }}"
    group: "{{ himation_group }}"
    mode: 0644
  notify:
    - reload himation

- name: create a profile script to customize the application user's environment
  template:
    src: profile.j2
    dest: "{{ himation_user_custom_profile }}"
    owner: "{{ himation_user }}"
    group: "{{ himation_group }}"
    mode: 0600

- name: ensure that the application user loads the custom profile
  lineinfile:
    dest: "{{ himation_user_home_dir }}/.profile"
    line: ". {{ himation_user_custom_profile }}"
    state: present
    owner: "{{ himation_user }}"
    group: "{{ himation_group }}"
    mode: 0600
