---
- name: disable all access by default
  ufw:
    policy: deny
    state: enabled

- name: ensure SSH is available
  ufw:
    rule: allow
    port: "{{ firewall_ssh_port }}"
    proto: tcp

- name: expose custom TCP ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items: "{{ firewall_tcp_ports }}"

- name: expose custom UDP ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: udp
  with_items: "{{ firewall_udp_ports }}"
