---
- name: disable all access by default
  ufw:
    policy: deny
    state: enabled

- name: ensure that SSH is allowed
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: update ports
  ufw:
    rule: "{{ item.allow | default(True) | ternary('allow', 'deny') }}"
    port: "{{ item.port }}"
    proto: "{{ item.protocol | default('tcp') }}"
  with_items: "{{ firewall_ports }}"
