---
- name: disable all access by default
  ufw:
    policy: deny
    state: enabled

- name: ensure SSH is available
  ufw:
    rule: allow
    port: "{{ firewall_ssh_port }}"
    proto: tcp

- name: expose custom ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items: "{{ firewall_ports }}"

