Vagrant.configure(2) do |config|

  require_relative "../fibula"

  config.vm.define("production", primary: true) do |config|
    config.vm.box = "fibula/ubuntu-14.04"
    config.vm.hostname = Fibula.hostname("www")

    config.hostsupdater.aliases = [Fibula.hostname("data")]
    config.hostsupdater.remove_on_suspend = false

    config.vm.network "private_network", ip: "10.30.30.30"

    config.ssh.insert_key = false
    config.ssh.private_key_path = Fibula.private_key_path
    config.ssh.forward_agent = false

    config.vm.provider "virtualbox" do |vbox|
      vbox.cpus = 1
      vbox.memory = 1024

      Fibula.virtualbox_networking_optimizations.each do |optimization|
        vbox.customize optimization
      end
    end

  end

end
