---
postfix_aliases_file: /etc/aliases
postfix_data_dir: /var/spool/postfix
postfix_pidfile: "{{ postfix_data_dir }}/pid/master.pid"
postfix_sasl_passwd: /etc/postfix/sasl_passwd
postfix_virtual_aliases_file: /etc/postfix/virtual
postfix_virtual_regexp: /etc/postfix/virtual_regexp
