---
- name: reload himation
  service:
    name: himation
    state: reloaded
  when: himation_daemonize
  notify:
    - refresh the himation cache

- name: restart himation
  service:
    name: himation
    state: restarted
  when: himation_daemonize
  notify:
    - refresh the himation cache

- name: refresh the himation cache
  command: npm run refresh-cache
  args:
    chdir: "{{ himation_current_source_dir }}"
  environment:
    HIMATION_CONFIG_FILE: "{{ himation_config_file }}"
  become: yes
  become_user: "{{ himation_user }}"
  when: himation_use_caching
