---
- name: create the domain directory
  file:
    path: "{{ certbot_domains_dir }}/{{ certbot_domain }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: create a static private key
  copy:
    dest: "{{ certbot_domains_dir }}/{{ certbot_domain }}/{{ certbot_key_file_name }}"
    content: "{{ certbot_static_key }}\n"
    owner: root
    group: root
    mode: 0600

- name: create a static certificate
  copy:
    dest: "{{ certbot_domains_dir }}/{{ certbot_domain }}/{{ certbot_certificate_file_name }}"
    content: "{{ certbot_static_certificate }}\n"
    owner: root
    group: root
    mode: 0600
