---
- name: grant nginx access to the chiton socket
  user:
    name: "{{ nginx_user }}"
    groups: "{{ chiton_group }}"
    append: yes

- name: check if the nginx site config exists
  stat:
    path: "{{ app_server_nginx_site_chiton }}"
  register: app_server_check_chiton_site
  changed_when: False

- name: create the nginx site config
  template:
    src: nginx/chiton.conf.j2
    dest: "{{ app_server_nginx_site_chiton }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx

- name: apply a new site config
  service:
    name: nginx
    state: restarted
  when: app_server_check_chiton_site.stat.isreg is not defined

- name: create a monit config
  template:
    src: monit/chiton.conf.j2
    dest: "{{ app_server_monit_config_chiton }}"
    mode: 0600
    owner: "{{ monit_user }}"
    group: "{{ monit_group }}"
  when: chiton_daemonize
  notify:
    - reload monit

- name: delete the monit config
  file:
    path: "{{ app_server_monit_config_chiton }}"
    state: absent
  when: not chiton_daemonize
  notify:
    - reload monit
