---
- name: monitor all services with monit
  template:
    src: "monit/{{ item }}.conf"
    dest: "{{ monit_configs_dir }}/{{ item }}.conf"
    owner: root
    group: root
    mode: 0644
  when: app_server_enable_monitoring
  notify:
    - reload monit
  with_items:
    - nginx
    - postfix
    - postgres
