---
- name: create a file for the SSL certificate
  copy:
    dest: "{{ app_server_ssl_certificate_path }}"
    content: "{{ cyb_certificates_wildcard_certificate | require_value }}"
    owner: root
    group: root
    mode: 0600
  no_log: yes
  notify:
    - reload nginx

- name: create a file for the SSL private key
  copy:
    dest: "{{ app_server_ssl_certificate_key_path }}"
    content: "{{ cyb_certificates_wildcard_key | require_value }}"
    owner: root
    group: root
    mode: 0600
  no_log: yes
  notify:
    - reload nginx
